using System.Text;

namespace Vrs.Core.Export;

public sealed partial class LuauExporter
{
    private static void AppendReadableEssentialsRuntime(StringBuilder builder, bool includeClockAndPlayer)
    {
        if (includeClockAndPlayer)
        {
            builder.AppendLine();
            builder.AppendLine("local function vrsNow()");
            builder.AppendLine("    if os ~= nil and os.clock ~= nil then");
            builder.AppendLine("        return os.clock()");
            builder.AppendLine("    end");
            builder.AppendLine("    if time ~= nil then");
            builder.AppendLine("        return time()");
            builder.AppendLine("    end");
            builder.AppendLine("    return 0");
            builder.AppendLine("end");
            builder.AppendLine();
            builder.AppendLine("local function vrsPlayerKey(player)");
            builder.AppendLine("    if player == nil then");
            builder.AppendLine("        return \"\"");
            builder.AppendLine("    end");
            builder.AppendLine("    if player.UserID ~= nil then");
            builder.AppendLine("        return tostring(player.UserID)");
            builder.AppendLine("    end");
            builder.AppendLine("    if player.UserId ~= nil then");
            builder.AppendLine("        return tostring(player.UserId)");
            builder.AppendLine("    end");
            builder.AppendLine("    if player.Name ~= nil then");
            builder.AppendLine("        return tostring(player.Name)");
            builder.AppendLine("    end");
            builder.AppendLine("    return tostring(player)");
            builder.AppendLine("end");
        }

        builder.AppendLine();
        builder.AppendLine("local function vrsValueAxis(value, upperName, lowerName, fallback)");
        builder.AppendLine("    if value == nil then");
        builder.AppendLine("        return fallback");
        builder.AppendLine("    end");
        builder.AppendLine("    if value[upperName] ~= nil then");
        builder.AppendLine("        return value[upperName]");
        builder.AppendLine("    end");
        builder.AppendLine("    if value[lowerName] ~= nil then");
        builder.AppendLine("        return value[lowerName]");
        builder.AppendLine("    end");
        builder.AppendLine("    return fallback");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsDistanceBetweenPositions(first, second)");
        builder.AppendLine("    local dx = vrsValueAxis(first, \"X\", \"x\", 0) - vrsValueAxis(second, \"X\", \"x\", 0)");
        builder.AppendLine("    local dy = vrsValueAxis(first, \"Y\", \"y\", 0) - vrsValueAxis(second, \"Y\", \"y\", 0)");
        builder.AppendLine("    local dz = vrsValueAxis(first, \"Z\", \"z\", 0) - vrsValueAxis(second, \"Z\", \"z\", 0)");
        builder.AppendLine("    return math.sqrt((dx * dx) + (dy * dy) + (dz * dz))");
        builder.AppendLine("end");
    }

    private static void AppendReadableObbyPlayerStateRuntime(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("local function vrsNow()");
        builder.AppendLine("    if os ~= nil and os.clock ~= nil then");
        builder.AppendLine("        return os.clock()");
        builder.AppendLine("    end");
        builder.AppendLine("    if time ~= nil then");
        builder.AppendLine("        return time()");
        builder.AppendLine("    end");
        builder.AppendLine("    return 0");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsPlayerKey(player)");
        builder.AppendLine("    if player == nil then");
        builder.AppendLine("        return \"\"");
        builder.AppendLine("    end");
        builder.AppendLine("    if player.UserID ~= nil then");
        builder.AppendLine("        return tostring(player.UserID)");
        builder.AppendLine("    end");
        builder.AppendLine("    if player.Name ~= nil then");
        builder.AppendLine("        return tostring(player.Name)");
        builder.AppendLine("    end");
        builder.AppendLine("    return tostring(player)");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsPlayerData(player)");
        builder.AppendLine("    local key = vrsPlayerKey(player)");
        builder.AppendLine("    if key == \"\" then");
        builder.AppendLine("        return nil");
        builder.AppendLine("    end");
        builder.AppendLine("    if VRS.playerState[key] == nil then");
        builder.AppendLine("        VRS.playerState[key] = { numbers = {}, texts = {}, flags = {}, collectibles = {} }");
        builder.AppendLine("    end");
        builder.AppendLine("    return VRS.playerState[key]");
        builder.AppendLine("end");
    }

    private static void AppendReadableObbyTouchResolver(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("local function vrsResolveTouchingPlayer(hit)");
        builder.AppendLine("    if hit == nil then");
        builder.AppendLine("        return nil");
        builder.AppendLine("    end");
        builder.AppendLine("    if hit.UserID ~= nil or hit.Respawn ~= nil or hit.Jump ~= nil then");
        builder.AppendLine("        return hit");
        builder.AppendLine("    end");
        builder.AppendLine("    if hit.Player ~= nil then");
        builder.AppendLine("        return hit.Player");
        builder.AppendLine("    end");
        builder.AppendLine("    if hit.Owner ~= nil and (hit.Owner.UserID ~= nil or hit.Owner.Respawn ~= nil or hit.Owner.Jump ~= nil) then");
        builder.AppendLine("        return hit.Owner");
        builder.AppendLine("    end");
        builder.AppendLine("    local parent = hit.Parent");
        builder.AppendLine("    if parent ~= nil then");
        builder.AppendLine("        if parent.UserID ~= nil or parent.Respawn ~= nil or parent.Jump ~= nil then");
        builder.AppendLine("            return parent");
        builder.AppendLine("        end");
        builder.AppendLine("        if parent.Player ~= nil then");
        builder.AppendLine("            return parent.Player");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    return nil");
        builder.AppendLine("end");
    }

    private static void AppendReadableObbyObjectPositionRuntime(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("local function vrsObjectPosition(object)");
        builder.AppendLine("    if object == nil then");
        builder.AppendLine("        return nil");
        builder.AppendLine("    end");
        builder.AppendLine("    if object.Position ~= nil then");
        builder.AppendLine("        return object.Position");
        builder.AppendLine("    end");
        builder.AppendLine("    if object.Parent ~= nil and object.Parent.Position ~= nil then");
        builder.AppendLine("        return object.Parent.Position");
        builder.AppendLine("    end");
        builder.AppendLine("    return nil");
        builder.AppendLine("end");
    }

    private static void AppendReadableVectorFactory(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("local function makeVector2(x, y)");
        builder.AppendLine("    if Vector2 ~= nil and Vector2.New ~= nil then");
        builder.AppendLine("        return Vector2.New(x, y)");
        builder.AppendLine("    end");
        builder.AppendLine("    if Vector2 ~= nil and Vector2.new ~= nil then");
        builder.AppendLine("        return Vector2.new(x, y)");
        builder.AppendLine("    end");
        builder.AppendLine("    return { X = x, Y = y }");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsVector2Axis(value, upperAxis, lowerAxis, fallback)");
        builder.AppendLine("    if value == nil then");
        builder.AppendLine("        return fallback");
        builder.AppendLine("    end");
        builder.AppendLine("    if value[upperAxis] ~= nil then");
        builder.AppendLine("        return tonumber(value[upperAxis]) or fallback");
        builder.AppendLine("    end");
        builder.AppendLine("    if value[lowerAxis] ~= nil then");
        builder.AppendLine("        return tonumber(value[lowerAxis]) or fallback");
        builder.AppendLine("    end");
        builder.AppendLine("    return fallback");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsVector2Magnitude(value)");
        builder.AppendLine("    if value == nil then");
        builder.AppendLine("        return 0");
        builder.AppendLine("    end");
        builder.AppendLine("    if value.Magnitude ~= nil then");
        builder.AppendLine("        return tonumber(value.Magnitude) or 0");
        builder.AppendLine("    end");
        builder.AppendLine("    local x = vrsVector2Axis(value, \"X\", \"x\", 0)");
        builder.AppendLine("    local y = vrsVector2Axis(value, \"Y\", \"y\", 0)");
        builder.AppendLine("    return math.sqrt((x * x) + (y * y))");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsVector2Distance(first, second)");
        builder.AppendLine("    if Vector2 ~= nil and Vector2.Distance ~= nil then");
        builder.AppendLine("        local ok, distance = pcall(function()");
        builder.AppendLine("            return Vector2.Distance(first, second)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and distance ~= nil then");
        builder.AppendLine("            return tonumber(distance) or 0");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    local dx = vrsVector2Axis(first, \"X\", \"x\", 0) - vrsVector2Axis(second, \"X\", \"x\", 0)");
        builder.AppendLine("    local dy = vrsVector2Axis(first, \"Y\", \"y\", 0) - vrsVector2Axis(second, \"Y\", \"y\", 0)");
        builder.AppendLine("    return math.sqrt((dx * dx) + (dy * dy))");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsVector2Normalized(value)");
        builder.AppendLine("    if value ~= nil and value.Normalized ~= nil then");
        builder.AppendLine("        return value.Normalized");
        builder.AppendLine("    end");
        builder.AppendLine("    if Vector2 ~= nil and Vector2.Normalize ~= nil then");
        builder.AppendLine("        local ok, normalized = pcall(function()");
        builder.AppendLine("            return Vector2.Normalize(value)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and normalized ~= nil then");
        builder.AppendLine("            return normalized");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    local magnitude = vrsVector2Magnitude(value)");
        builder.AppendLine("    if magnitude == 0 then");
        builder.AppendLine("        return makeVector2(0, 0)");
        builder.AppendLine("    end");
        builder.AppendLine("    return makeVector2(vrsVector2Axis(value, \"X\", \"x\", 0) / magnitude, vrsVector2Axis(value, \"Y\", \"y\", 0) / magnitude)");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsVector2Lerp(fromValue, toValue, amount)");
        builder.AppendLine("    if Vector2 ~= nil and Vector2.Lerp ~= nil then");
        builder.AppendLine("        local ok, value = pcall(function()");
        builder.AppendLine("            return Vector2.Lerp(fromValue, toValue, amount)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and value ~= nil then");
        builder.AppendLine("            return value");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    local t = math.max(0, math.min(1, tonumber(amount) or 0))");
        builder.AppendLine("    local x = vrsVector2Axis(fromValue, \"X\", \"x\", 0) + ((vrsVector2Axis(toValue, \"X\", \"x\", 0) - vrsVector2Axis(fromValue, \"X\", \"x\", 0)) * t)");
        builder.AppendLine("    local y = vrsVector2Axis(fromValue, \"Y\", \"y\", 0) + ((vrsVector2Axis(toValue, \"Y\", \"y\", 0) - vrsVector2Axis(fromValue, \"Y\", \"y\", 0)) * t)");
        builder.AppendLine("    return makeVector2(x, y)");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function makeVector3(x, y, z)");
        builder.AppendLine("    if Vector3 ~= nil and Vector3.New ~= nil then");
        builder.AppendLine("        return Vector3.New(x, y, z)");
        builder.AppendLine("    end");
        builder.AppendLine("    if Vector3 ~= nil and Vector3.new ~= nil then");
        builder.AppendLine("        return Vector3.new(x, y, z)");
        builder.AppendLine("    end");
        builder.AppendLine("    return { X = x, Y = y, Z = z }");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsVector3Axis(value, upperAxis, lowerAxis, fallback)");
        builder.AppendLine("    if value == nil then");
        builder.AppendLine("        return fallback");
        builder.AppendLine("    end");
        builder.AppendLine("    if value[upperAxis] ~= nil then");
        builder.AppendLine("        return tonumber(value[upperAxis]) or fallback");
        builder.AppendLine("    end");
        builder.AppendLine("    if value[lowerAxis] ~= nil then");
        builder.AppendLine("        return tonumber(value[lowerAxis]) or fallback");
        builder.AppendLine("    end");
        builder.AppendLine("    return fallback");
        builder.AppendLine("end");
        builder.AppendLine();
        // ColorSeries is a real Polytoria value type, but the generated graph
        // keeps table fallbacks so color workflows remain diagnosable across
        // runtime builds that expose only part of the documented API.
        builder.AppendLine("local function vrsColorComponent(value, upperName, lowerName, fallback)");
        builder.AppendLine("    if value == nil then");
        builder.AppendLine("        return fallback");
        builder.AppendLine("    end");
        builder.AppendLine("    if value[upperName] ~= nil then");
        builder.AppendLine("        return tonumber(value[upperName]) or fallback");
        builder.AppendLine("    end");
        builder.AppendLine("    if value[lowerName] ~= nil then");
        builder.AppendLine("        return tonumber(value[lowerName]) or fallback");
        builder.AppendLine("    end");
        builder.AppendLine("    return fallback");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsLerpColor(first, second, amount)");
        builder.AppendLine("    local t = math.max(0, math.min(1, tonumber(amount) or 0))");
        builder.AppendLine("    return Color.New(");
        builder.AppendLine("        vrsColorComponent(first, \"R\", \"r\", 1) + ((vrsColorComponent(second, \"R\", \"r\", 1) - vrsColorComponent(first, \"R\", \"r\", 1)) * t),");
        builder.AppendLine("        vrsColorComponent(first, \"G\", \"g\", 1) + ((vrsColorComponent(second, \"G\", \"g\", 1) - vrsColorComponent(first, \"G\", \"g\", 1)) * t),");
        builder.AppendLine("        vrsColorComponent(first, \"B\", \"b\", 1) + ((vrsColorComponent(second, \"B\", \"b\", 1) - vrsColorComponent(first, \"B\", \"b\", 1)) * t),");
        builder.AppendLine("        vrsColorComponent(first, \"A\", \"a\", 1) + ((vrsColorComponent(second, \"A\", \"a\", 1) - vrsColorComponent(first, \"A\", \"a\", 1)) * t)");
        builder.AppendLine("    )");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsColorSeriesFromColors(minColor, maxColor)");
        builder.AppendLine("    if ColorSeries ~= nil and ColorSeries.New ~= nil then");
        builder.AppendLine("        local ok, value = pcall(function()");
        builder.AppendLine("            return ColorSeries.New(minColor, maxColor)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and value ~= nil then");
        builder.AppendLine("            return value");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    return { __vrsColorSeries = true, colors = { minColor, maxColor }, offsets = { 0, 1 }, PointCount = 2 }");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsColorSeriesColors(series)");
        builder.AppendLine("    if series ~= nil and series.GetColors ~= nil then");
        builder.AppendLine("        local ok, colors = pcall(function()");
        builder.AppendLine("            return series:GetColors()");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and colors ~= nil then");
        builder.AppendLine("            return colors");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    if series ~= nil and series.colors ~= nil then");
        builder.AppendLine("        return series.colors");
        builder.AppendLine("    end");
        builder.AppendLine("    return { Color.New(1, 1, 1, 1), Color.New(0, 0, 0, 1) }");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsColorSeriesOffsets(series)");
        builder.AppendLine("    if series ~= nil and series.GetOffsets ~= nil then");
        builder.AppendLine("        local ok, offsets = pcall(function()");
        builder.AppendLine("            return series:GetOffsets()");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and offsets ~= nil then");
        builder.AppendLine("            return offsets");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    if series ~= nil and series.offsets ~= nil then");
        builder.AppendLine("        return series.offsets");
        builder.AppendLine("    end");
        builder.AppendLine("    return { 0, 1 }");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsColorSeriesPointCount(series)");
        builder.AppendLine("    if series ~= nil and series.PointCount ~= nil then");
        builder.AppendLine("        return tonumber(series.PointCount) or 0");
        builder.AppendLine("    end");
        builder.AppendLine("    return #vrsColorSeriesColors(series)");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsColorSeriesColorAt(series, point)");
        builder.AppendLine("    if series ~= nil and series.GetColor ~= nil then");
        builder.AppendLine("        local ok, color = pcall(function()");
        builder.AppendLine("            return series:GetColor(point)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and color ~= nil then");
        builder.AppendLine("            return color");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    local colors = vrsColorSeriesColors(series)");
        builder.AppendLine("    local index = math.floor(tonumber(point) or 1)");
        builder.AppendLine("    if index < 1 then");
        builder.AppendLine("        index = index + 1");
        builder.AppendLine("    end");
        builder.AppendLine("    return colors[index] or colors[1] or Color.New(1, 1, 1, 1)");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsColorSeriesOffsetAt(series, point)");
        builder.AppendLine("    if series ~= nil and series.GetOffset ~= nil then");
        builder.AppendLine("        local ok, offset = pcall(function()");
        builder.AppendLine("            return series:GetOffset(point)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and offset ~= nil then");
        builder.AppendLine("            return tonumber(offset) or 0");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    local offsets = vrsColorSeriesOffsets(series)");
        builder.AppendLine("    local index = math.floor(tonumber(point) or 1)");
        builder.AppendLine("    if index < 1 then");
        builder.AppendLine("        index = index + 1");
        builder.AppendLine("    end");
        builder.AppendLine("    return tonumber(offsets[index]) or 0");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsColorSeriesLerp(series, amount)");
        builder.AppendLine("    if series ~= nil and series.Lerp ~= nil then");
        builder.AppendLine("        local ok, color = pcall(function()");
        builder.AppendLine("            return series:Lerp(amount)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and color ~= nil then");
        builder.AppendLine("            return color");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    local count = math.max(1, vrsColorSeriesPointCount(series))");
        builder.AppendLine("    return vrsLerpColor(vrsColorSeriesColorAt(series, 1), vrsColorSeriesColorAt(series, count), amount)");
        builder.AppendLine("end");
        builder.AppendLine();
        // Quaternion helpers call the official Polytoria API first and keep
        // minimal fallbacks so generated scripts fail softly if a method is
        // missing in a Creator/runtime build.
        builder.AppendLine("local function makeQuaternion(x, y, z, w)");
        builder.AppendLine("    if Quaternion ~= nil and Quaternion.New ~= nil then");
        builder.AppendLine("        return Quaternion.New(x, y, z, w)");
        builder.AppendLine("    end");
        builder.AppendLine("    if Quaternion ~= nil and Quaternion.new ~= nil then");
        builder.AppendLine("        return Quaternion.new(x, y, z, w)");
        builder.AppendLine("    end");
        builder.AppendLine("    return { X = x, Y = y, Z = z, W = w }");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsQuaternionComponent(value, upperAxis, lowerAxis, fallback)");
        builder.AppendLine("    if value == nil then");
        builder.AppendLine("        return fallback");
        builder.AppendLine("    end");
        builder.AppendLine("    if value[upperAxis] ~= nil then");
        builder.AppendLine("        return tonumber(value[upperAxis]) or fallback");
        builder.AppendLine("    end");
        builder.AppendLine("    if value[lowerAxis] ~= nil then");
        builder.AppendLine("        return tonumber(value[lowerAxis]) or fallback");
        builder.AppendLine("    end");
        builder.AppendLine("    return fallback");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsQuaternionIdentity()");
        builder.AppendLine("    if Quaternion ~= nil and Quaternion.Identity ~= nil then");
        builder.AppendLine("        return Quaternion.Identity");
        builder.AppendLine("    end");
        builder.AppendLine("    return makeQuaternion(0, 0, 0, 1)");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsQuaternionMagnitude(value)");
        builder.AppendLine("    local x = vrsQuaternionComponent(value, \"X\", \"x\", 0)");
        builder.AppendLine("    local y = vrsQuaternionComponent(value, \"Y\", \"y\", 0)");
        builder.AppendLine("    local z = vrsQuaternionComponent(value, \"Z\", \"z\", 0)");
        builder.AppendLine("    local w = vrsQuaternionComponent(value, \"W\", \"w\", 1)");
        builder.AppendLine("    return math.sqrt((x * x) + (y * y) + (z * z) + (w * w))");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsQuaternionNormalize(value)");
        builder.AppendLine("    if Quaternion ~= nil and Quaternion.Normalize ~= nil then");
        builder.AppendLine("        local ok, normalized = pcall(function()");
        builder.AppendLine("            return Quaternion.Normalize(value)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and normalized ~= nil then");
        builder.AppendLine("            return normalized");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    local magnitude = vrsQuaternionMagnitude(value)");
        builder.AppendLine("    if magnitude == 0 then");
        builder.AppendLine("        return vrsQuaternionIdentity()");
        builder.AppendLine("    end");
        builder.AppendLine("    return makeQuaternion(");
        builder.AppendLine("        vrsQuaternionComponent(value, \"X\", \"x\", 0) / magnitude,");
        builder.AppendLine("        vrsQuaternionComponent(value, \"Y\", \"y\", 0) / magnitude,");
        builder.AppendLine("        vrsQuaternionComponent(value, \"Z\", \"z\", 0) / magnitude,");
        builder.AppendLine("        vrsQuaternionComponent(value, \"W\", \"w\", 1) / magnitude");
        builder.AppendLine("    )");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsQuaternionFromEuler(euler)");
        builder.AppendLine("    if Quaternion ~= nil and Quaternion.Euler ~= nil then");
        builder.AppendLine("        local ok, value = pcall(function()");
        builder.AppendLine("            return Quaternion.Euler(euler)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and value ~= nil then");
        builder.AppendLine("            return value");
        builder.AppendLine("        end");
        builder.AppendLine("        local x = vrsVector3Axis(euler, \"X\", \"x\", 0)");
        builder.AppendLine("        local y = vrsVector3Axis(euler, \"Y\", \"y\", 0)");
        builder.AppendLine("        local z = vrsVector3Axis(euler, \"Z\", \"z\", 0)");
        builder.AppendLine("        ok, value = pcall(function()");
        builder.AppendLine("            return Quaternion.Euler(x, y, z)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and value ~= nil then");
        builder.AppendLine("            return value");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    return vrsQuaternionIdentity()");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsQuaternionToEuler(rotation)");
        builder.AppendLine("    if Quaternion ~= nil and Quaternion.ToEuler ~= nil then");
        builder.AppendLine("        local ok, value = pcall(function()");
        builder.AppendLine("            return Quaternion.ToEuler(rotation)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and value ~= nil then");
        builder.AppendLine("            return value");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    return makeVector3(0, 0, 0)");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsQuaternionDot(first, second)");
        builder.AppendLine("    if Quaternion ~= nil and Quaternion.Dot ~= nil then");
        builder.AppendLine("        local ok, value = pcall(function()");
        builder.AppendLine("            return Quaternion.Dot(first, second)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and value ~= nil then");
        builder.AppendLine("            return tonumber(value) or 0");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    return (vrsQuaternionComponent(first, \"X\", \"x\", 0) * vrsQuaternionComponent(second, \"X\", \"x\", 0)) +");
        builder.AppendLine("        (vrsQuaternionComponent(first, \"Y\", \"y\", 0) * vrsQuaternionComponent(second, \"Y\", \"y\", 0)) +");
        builder.AppendLine("        (vrsQuaternionComponent(first, \"Z\", \"z\", 0) * vrsQuaternionComponent(second, \"Z\", \"z\", 0)) +");
        builder.AppendLine("        (vrsQuaternionComponent(first, \"W\", \"w\", 1) * vrsQuaternionComponent(second, \"W\", \"w\", 1))");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsQuaternionAngle(first, second)");
        builder.AppendLine("    if Quaternion ~= nil and Quaternion.Angle ~= nil then");
        builder.AppendLine("        local ok, value = pcall(function()");
        builder.AppendLine("            return Quaternion.Angle(first, second)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and value ~= nil then");
        builder.AppendLine("            return tonumber(value) or 0");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    local dot = math.abs(vrsQuaternionDot(vrsQuaternionNormalize(first), vrsQuaternionNormalize(second)))");
        builder.AppendLine("    dot = math.max(-1, math.min(1, dot))");
        builder.AppendLine("    return math.deg(math.acos(dot)) * 2");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsQuaternionLerp(first, second, amount)");
        builder.AppendLine("    if Quaternion ~= nil and Quaternion.Lerp ~= nil then");
        builder.AppendLine("        local ok, value = pcall(function()");
        builder.AppendLine("            return Quaternion.Lerp(first, second, amount)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and value ~= nil then");
        builder.AppendLine("            return value");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    local t = math.max(0, math.min(1, tonumber(amount) or 0))");
        builder.AppendLine("    return vrsQuaternionNormalize(makeQuaternion(");
        builder.AppendLine("        vrsQuaternionComponent(first, \"X\", \"x\", 0) + ((vrsQuaternionComponent(second, \"X\", \"x\", 0) - vrsQuaternionComponent(first, \"X\", \"x\", 0)) * t),");
        builder.AppendLine("        vrsQuaternionComponent(first, \"Y\", \"y\", 0) + ((vrsQuaternionComponent(second, \"Y\", \"y\", 0) - vrsQuaternionComponent(first, \"Y\", \"y\", 0)) * t),");
        builder.AppendLine("        vrsQuaternionComponent(first, \"Z\", \"z\", 0) + ((vrsQuaternionComponent(second, \"Z\", \"z\", 0) - vrsQuaternionComponent(first, \"Z\", \"z\", 0)) * t),");
        builder.AppendLine("        vrsQuaternionComponent(first, \"W\", \"w\", 1) + ((vrsQuaternionComponent(second, \"W\", \"w\", 1) - vrsQuaternionComponent(first, \"W\", \"w\", 1)) * t)");
        builder.AppendLine("    ))");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsQuaternionSlerp(first, second, amount)");
        builder.AppendLine("    if Quaternion ~= nil and Quaternion.Slerp ~= nil then");
        builder.AppendLine("        local ok, value = pcall(function()");
        builder.AppendLine("            return Quaternion.Slerp(first, second, amount)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and value ~= nil then");
        builder.AppendLine("            return value");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    return vrsQuaternionLerp(first, second, amount)");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsQuaternionInverse(rotation)");
        builder.AppendLine("    if Quaternion ~= nil and Quaternion.Inverse ~= nil then");
        builder.AppendLine("        local ok, value = pcall(function()");
        builder.AppendLine("            return Quaternion.Inverse(rotation)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and value ~= nil then");
        builder.AppendLine("            return value");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    return makeQuaternion(");
        builder.AppendLine("        -vrsQuaternionComponent(rotation, \"X\", \"x\", 0),");
        builder.AppendLine("        -vrsQuaternionComponent(rotation, \"Y\", \"y\", 0),");
        builder.AppendLine("        -vrsQuaternionComponent(rotation, \"Z\", \"z\", 0),");
        builder.AppendLine("        vrsQuaternionComponent(rotation, \"W\", \"w\", 1)");
        builder.AppendLine("    )");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsQuaternionFromAxisAngle(axis, angle)");
        builder.AppendLine("    if Quaternion ~= nil and Quaternion.AngleAxis ~= nil then");
        builder.AppendLine("        local ok, value = pcall(function()");
        builder.AppendLine("            return Quaternion.AngleAxis(angle, axis)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and value ~= nil then");
        builder.AppendLine("            return value");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    return vrsQuaternionIdentity()");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsQuaternionLookRotation(forward, upwards)");
        builder.AppendLine("    if Quaternion ~= nil and Quaternion.LookRotation ~= nil then");
        builder.AppendLine("        local ok, value = pcall(function()");
        builder.AppendLine("            return Quaternion.LookRotation(forward, upwards)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and value ~= nil then");
        builder.AppendLine("            return value");
        builder.AppendLine("        end");
        builder.AppendLine("        ok, value = pcall(function()");
        builder.AppendLine("            return Quaternion.LookRotation(forward)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and value ~= nil then");
        builder.AppendLine("            return value");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    return vrsQuaternionIdentity()");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsQuaternionFromToRotation(fromDirection, toDirection)");
        builder.AppendLine("    if Quaternion ~= nil and Quaternion.FromToRotation ~= nil then");
        builder.AppendLine("        local ok, value = pcall(function()");
        builder.AppendLine("            return Quaternion.FromToRotation(fromDirection, toDirection)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and value ~= nil then");
        builder.AppendLine("            return value");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    return vrsQuaternionIdentity()");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsQuaternionRotateTowards(fromRotation, toRotation, maxDegreesDelta)");
        builder.AppendLine("    if Quaternion ~= nil and Quaternion.RotateTowards ~= nil then");
        builder.AppendLine("        local ok, value = pcall(function()");
        builder.AppendLine("            return Quaternion.RotateTowards(fromRotation, toRotation, maxDegreesDelta)");
        builder.AppendLine("        end)");
        builder.AppendLine("        if ok and value ~= nil then");
        builder.AppendLine("            return value");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine("    local angle = vrsQuaternionAngle(fromRotation, toRotation)");
        builder.AppendLine("    if angle <= 0 then");
        builder.AppendLine("        return toRotation");
        builder.AppendLine("    end");
        builder.AppendLine("    return vrsQuaternionSlerp(fromRotation, toRotation, math.max(0, tonumber(maxDegreesDelta) or 0) / angle)");
        builder.AppendLine("end");
    }

    private static void AppendReadableVectorTweenRuntime(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("local function vrsVectorAxis(value, upperName, lowerName, fallback)");
        builder.AppendLine("    if value == nil then");
        builder.AppendLine("        return fallback");
        builder.AppendLine("    end");
        builder.AppendLine("    if value[upperName] ~= nil then");
        builder.AppendLine("        return value[upperName]");
        builder.AppendLine("    end");
        builder.AppendLine("    if value[lowerName] ~= nil then");
        builder.AppendLine("        return value[lowerName]");
        builder.AppendLine("    end");
        builder.AppendLine("    return fallback");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsLerpNumber(startValue, endValue, alpha)");
        builder.AppendLine("    return startValue + ((endValue - startValue) * alpha)");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsLerpVector3(startValue, endValue, alpha)");
        builder.AppendLine("    return makeVector3(");
        builder.AppendLine("        vrsLerpNumber(vrsVectorAxis(startValue, \"X\", \"x\", 0), vrsVectorAxis(endValue, \"X\", \"x\", 0), alpha),");
        builder.AppendLine("        vrsLerpNumber(vrsVectorAxis(startValue, \"Y\", \"y\", 0), vrsVectorAxis(endValue, \"Y\", \"y\", 0), alpha),");
        builder.AppendLine("        vrsLerpNumber(vrsVectorAxis(startValue, \"Z\", \"z\", 0), vrsVectorAxis(endValue, \"Z\", \"z\", 0), alpha)");
        builder.AppendLine("    )");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsEaseIn(alpha, smoothing)");
        builder.AppendLine("    if smoothing == \"Sine\" then");
        builder.AppendLine("        return 1 - math.cos((alpha * 3.141592653589793) / 2)");
        builder.AppendLine("    elseif smoothing == \"Quad\" then");
        builder.AppendLine("        return alpha * alpha");
        builder.AppendLine("    elseif smoothing == \"Cubic\" then");
        builder.AppendLine("        return alpha * alpha * alpha");
        builder.AppendLine("    end");
        builder.AppendLine("    return alpha");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsEase(alpha, smoothing, direction)");
        builder.AppendLine("    if direction == \"In\" then");
        builder.AppendLine("        return vrsEaseIn(alpha, smoothing)");
        builder.AppendLine("    elseif direction == \"Out\" then");
        builder.AppendLine("        return 1 - vrsEaseIn(1 - alpha, smoothing)");
        builder.AppendLine("    end");
        builder.AppendLine("    if alpha < 0.5 then");
        builder.AppendLine("        return vrsEaseIn(alpha * 2, smoothing) / 2");
        builder.AppendLine("    end");
        builder.AppendLine("    return 1 - (vrsEaseIn((1 - alpha) * 2, smoothing) / 2)");
        builder.AppendLine("end");
        builder.AppendLine();
        builder.AppendLine("local function vrsRunVectorTween(readValue, writeValue, endValue, duration, smoothing, direction)");
        builder.AppendLine("    if duration == nil or duration <= 0 then");
        builder.AppendLine("        writeValue(endValue)");
        builder.AppendLine("        return");
        builder.AppendLine("    end");
        builder.AppendLine("    local startValue = readValue()");
        builder.AppendLine("    local elapsed = 0");
        builder.AppendLine("    local stepSeconds = 0.03");
        builder.AppendLine("    while elapsed < duration do");
        builder.AppendLine("        wait(stepSeconds)");
        builder.AppendLine("        elapsed = elapsed + stepSeconds");
        builder.AppendLine("        local alpha = math.min(elapsed / duration, 1)");
        builder.AppendLine("        writeValue(vrsLerpVector3(startValue, endValue, vrsEase(alpha, smoothing, direction)))");
        builder.AppendLine("    end");
        builder.AppendLine("    writeValue(endValue)");
        builder.AppendLine("end");
    }

    private static void AppendReadableTargetResolver(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine("local function resolveTarget(triggerObject, targetName)");
        builder.AppendLine("    if targetName == nil or targetName == \"\" or targetName == \"Self\" or targetName == \"Target\" then");
        builder.AppendLine("        return triggerObject");
        builder.AppendLine("    end");
        builder.AppendLine();
        builder.AppendLine("    local current = nil");
        builder.AppendLine("    for segment in string.gmatch(targetName, \"[^/]+\") do");
        builder.AppendLine("        if current == nil then");
        builder.AppendLine("            if segment == \"World\" and World ~= nil then");
        builder.AppendLine("                current = World");
        builder.AppendLine("            elseif segment == \"PlayerGUI\" and PlayerGUI ~= nil then");
        builder.AppendLine("                current = PlayerGUI");
        builder.AppendLine("            elseif segment == \"Environment\" and Environment ~= nil then");
        builder.AppendLine("                current = Environment");
        builder.AppendLine("            elseif segment == \"Hidden\" and Hidden ~= nil then");
        builder.AppendLine("                current = Hidden");
        builder.AppendLine("            elseif segment == \"ScriptService\" and ScriptService ~= nil then");
        builder.AppendLine("                current = ScriptService");
        builder.AppendLine("            elseif triggerObject ~= nil and triggerObject.FindChild ~= nil then");
        builder.AppendLine("                current = triggerObject:FindChild(segment)");
        builder.AppendLine("            elseif World ~= nil and World.FindChild ~= nil then");
        builder.AppendLine("                current = World:FindChild(segment)");
        builder.AppendLine("            end");
        builder.AppendLine("        elseif current.FindChild ~= nil then");
        builder.AppendLine("            current = current:FindChild(segment)");
        builder.AppendLine("        else");
        builder.AppendLine("            return nil");
        builder.AppendLine("        end");
        builder.AppendLine();
        builder.AppendLine("        if current == nil then");
        builder.AppendLine("            return nil");
        builder.AppendLine("        end");
        builder.AppendLine("    end");
        builder.AppendLine();
        builder.AppendLine("    return current");
        builder.AppendLine("end");
    }
}
